services:
  radium-mongodb:
    image: mongo:7.0
    container_name: radium-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - radium_mongodb_data:/data/db
    networks:
      - radium-network

  radium-redis:
    image: redis:7.2-alpine
    container_name: radium-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - radium_redis_data:/data
    networks:
      - radium-network

volumes:
  radium_mongodb_data:
    driver: local
  radium_redis_data:
    driver: local

networks:
  radium-network:
    driver: bridge
